version: '3.8'

# Load environment variables from .env file
env_file:
  - .env

services:
  user-db:
    image: postgres:15
    environment:
      POSTGRES_DB: users
      POSTGRES_USER: kibria
      POSTGRES_PASSWORD: kibria
    ports:
      - "5450:5432"
    volumes:
      - user_db_data:/var/lib/postgresql/data
    networks:
      - library-network

  user-service:
    build: ./user_service
    ports:
      - "8001:8001"
    environment:
      - DATABASE_URL=${DATABASE_URL}
    depends_on:
      - user-db
    networks:
      - library-network

  book-service:
    build: ./book_service
    ports:
      - "8002:8002"
    environment:
      - DATABASE_URL=${DATABASE_URL}
    networks:
      - library-network

  loan-service:
    build: ./loan_service
    ports:
      - "8003:8003"
    environment:
      - DATABASE_URL=${DATABASE_URL}
      - USER_SERVICE_URL=${USER_SERVICE_URL}
      - BOOK_SERVICE_URL=${BOOK_SERVICE_URL}
    depends_on:
      - user-service
      - book-service
    networks:
      - library-network

networks:
  library-network:
    driver: bridge

volumes:
  user_db_data:
