version: '3.8'

services:
  user-service:
    build: ./user_service
    ports:
      - "8001:8001"
    environment:
      - DATABASE_URL=postgresql+asyncpg://neondb_owner:npg_4ixBAKfGX1PW@ep-round-dust-a1usofig-pooler.ap-southeast-1.aws.neon.tech/neondb?ssl=require
    networks:
      - library-network

  book-service:
    build: ./book_service
    ports:
      - "8002:8002"
    environment:
      - DATABASE_URL=postgresql+asyncpg://neondb_owner:npg_4ixBAKfGX1PW@ep-round-dust-a1usofig-pooler.ap-southeast-1.aws.neon.tech/neondb?ssl=require
    networks:
      - library-network

  loan-service:
    build: ./loan_service
    ports:
      - "8003:8003"
    environment:
      - DATABASE_URL=postgresql+asyncpg://neondb_owner:npg_4ixBAKfGX1PW@ep-round-dust-a1usofig-pooler.ap-southeast-1.aws.neon.tech/neondb?ssl=require
      - USER_SERVICE_URL=http://user-service:8001
      - BOOK_SERVICE_URL=http://book-service:8002
    depends_on:
      - user-service
      - book-service
    networks:
      - library-network

networks:
  library-network:
    driver: bridge
